import axios from 'axios';
import createMemeIdea from '@wasp/actions/createMemeIdea.js';
import type { AutoMemeIdea } from '@wasp/entities';

export const getMemeTemplates = async (_args: any, context: any) => {
  console.log('.... ><><>< get meme templates cron starting ><><>< ....');

  const response = await axios.get('https://api.imgflip.com/get_memes');

  response.data.data.memes.forEach(async (meme: any) => {
    await context.entities.Template.upsert({
      where: { id: meme.id },
      create: {
        id: meme.id,
        name: meme.name,
        url: meme.url,
        width: meme.width,
        height: meme.height,
        boxCount: meme.box_count,
      },
      update: {},
    });
  });
};

export const runAutoMemes = async (args: { topics: string[]; audience: string }, context: any) => {
  console.log('.... ><><>< auto memes cron starting ><><>< ....');

  const ideas = await context.entities.AutoMemeIdea.findMany({
    where: {
      OR: [
        {
          stopDate: {
            gt: new Date(),
          },
        },
        {
          stopDate: null,
        },
      ],
    },
  });

  const autoGeneratedMemes = await Promise.allSettled(
    ideas.map(async (idea: AutoMemeIdea) => {
      const meme = await createMemeIdea(
        {
          topics: idea.topics,
          audience: idea.audience,
          autoMemeIdeaId: idea.id
        },
        context
      );
    })
  );

  console.log('.... ><><>< auto memes cron finished ><><>< ....', autoGeneratedMemes)
};
